# Project Information
site_name: REDI
site_url: https://github.com/In-For-Disaster-Analytics/REDI-Documentation
site_author: UT Austin REDI Team
site_description:  >-
  Documenation for REDI products

# Repository
repo_name: In-For-Disaster-Analytics/REDI-Documentation
repo_url: https://github.com/In-For-Disaster-Analytics/REDI-Documentation

theme:
  name: material
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js  