# Project Information
site_name: REDI
site_url: https://in-for-disaster-analytics.github.io/REDI-Documentation/
site_author: UT Austin REDI Team
site_description:  >-
  Documenation for REDI products

# Repository
repo_name: In-For-Disaster-Analytics/REDI-Documentation
repo_url: https://github.com/In-For-Disaster-Analytics/REDI-Documentation

# Copyright
copyright: Copyright &copy; 2024 UT Austin IDA team

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs    
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.top
    - toc.follow
  font:
    text: Open Sans
    code: Roboto

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
  
    
extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js  

# plugins:
#   - privacy:
#       links_attr_map:
#         target: _blank

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true  

# Page tree
nav:
  - About:
    - about/index.md
    - Philosophy: about/philosophy.md
    - Concept Models: about/concept-models.md
    - Meet the Team: about/team.md
  - Integrated Solutions:  
    - integrated-solutions/index.md
    - DOLCE: integrated-solutions/dolce.md
    - DynaMo: integrated-solutions/dynamo.md
    - Digital Twins: integrated-solutions/digital-twins.md
  # - REDI Ecosystem:  
  #     - Integrated Solutions:  redi-ecosystem/integrated-solutions.md 
  #     - Data Ecosystem:  
  #         - Dynamo Model Catalog: redi-ecosystem/data-ecosystem/dynamo-model-catalog.md
  #         - DataX portal: redi-ecosystem/data-ecosystem/datax.md
  #         - Data:  
  #             - Data Discovery: redi-ecosystem/data-ecosystem/data/data-discovery.md  
  #             - Data Registration: redi-ecosystem/data-ecosystem/data/data-registration.md  
  #     - App Ecosystem:  
  #         - NNA Sites & Stories:  redi-ecosystem/app-ecosystem/sites-and-stories.md
  #         - Dynamo Cookbooks:  redi-ecosystem/app-ecosystem/dynamo-cookbooks.md
      # - Infrastructure Resources      
  - Projects:
    - NNA Alaska: projects/nna-alaska.md  
    - Subsidence: projects/subsidence.md   
    - SETx KMP: projects/setx.md   
    - RGV AI Enabled Modeling: projects/rgv.md   
  - Protocols:
    - protocols/index.md
    # - Drone: protocols/drone.md  
    # - Geoslam (Geoslam): protocols/geoslam.md
    - MINT: protocols/MINT/  
    - Survey123: protocols/survey123_user.md
  - Field Sessions: 
    - field-sessions/index.md
    - Fort Davis: 
      - Drone:  field-sessions/fort-davis-march-23/drone.md
      - LiDAR: field-sessions/fort-davis-march-23/lidar.md
