# Project Information
site_name: REDI
site_url: https://in-for-disaster-analytics.github.io/REDI-Documentation/
site_author: UT Austin REDI Team
site_description:  >-
  Documenation for REDI products

# Repository
repo_name: In-For-Disaster-Analytics/REDI-Documentation
repo_url: https://github.com/In-For-Disaster-Analytics/REDI-Documentation

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - toc.follow
  font:
    text: Open Sans
  palette:
    scheme: utexas
  
    
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js  

markdown_extensions:
  - toc:
      permalink: true  

# Page tree
nav:
  - Home: index.md
  - Projects:
    - Sites and Stories: sites.md
    - Digital Twins: twins.md
  - Protocols:
    - Survey123: protocols/survey123_user.md
  - Field Sessions: field-sessions/fort-davis.md