# Project Information
site_name: REDI
site_url: https://in-for-disaster-analytics.github.io/REDI-Documentation/
site_author: UT Austin REDI Team
site_description:  >-
  Documenation for REDI products

# Repository
repo_name: In-For-Disaster-Analytics/REDI-Documentation
repo_url: https://github.com/In-For-Disaster-Analytics/REDI-Documentation

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs    
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.footer
    - navigation.top
    - toc.follow
  font:
    text: Open Sans
    code: Roboto

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
  
    
extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js  

# plugins:
#   - privacy:
#       links_attr_map:
#         target: _blank

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true  

plugins:
    - search
    - awesome-pages      

# Page tree
